### PR TITLE
Powertool example

### PR DESCRIPTION
**Pull request by Pia007**
I have reviewed the Powertools example. While working through the actual example, received an error indicating that the 'examples', folder did not include an '__init__.py' file when the powertools quick start is initialized. Consulted with @jtfrench23 and added the file and the error was resolved. I Included 2 steps to add it at the beginning of the example.  Not sure if that's the best approach.

### CODE REVIEW

**Review by jtfrench23 — COMMENTED** [review]
I believe the init file just needs to be added to the template in the cdev sdk, I doubt we want the users having to add that file in manually

**Comment by Pia007** [comment]
> I believe the init file just needs to be added to the template in the cdev sdk, I doubt we want the users having to add that file in manually

I agree. This is the main issue in this example besides minor grammar edits. I could remove both steps and just submit it on the debugging channel. Thoughts?

**Review by DanielSanchez97 — CHANGES_REQUESTED** [review]
I added the __init__.py file to the cdev sdk template and merged it into the `dev` branch. 

Can you add the {{<header_divider>}} to line 12 so that it looks like the other exmaples? Once thats added it LGTM.

**Review by ianick87 — APPROVED** [review]

**Comment by Pia007** [comment]
> I added the **init**.py file to the cdev sdk template and merged it into the `dev` branch.
> 
> Can you add the {{<header_divider>}} to line 12 so that it looks like the other exmaples? Once thats added it LGTM.

I completely missed that. Thanks, Daniel. Just added the divider and will go ahead merge.

**Pull request merged**
