### PR TITLE
made updates to fullstack tutorial including linking the video

### PR DESCRIPTION
**Pull request by jtfrench23**

### CODE REVIEW

**Review by Pia007 — APPROVED** [review]
Looks good, Jordan and I watched the video. Nice job!

**Review by ianick87 — APPROVED** [review]

**Comment by jtfrench23** [comment]
I made some changes to the app.js section to hopefully make it easier, let me know if the clarifications are sufficient.  I refactored the code snippet so the user only has to make an update in one spot instead of 2

**Review by Pia007 — COMMENTED** [review]
Hi Jordan, I saw one minor spelling issue that I missed previously.

**Review by DanielSanchez97 — APPROVED** [review]
These changes LGTM

**Pull request merged**
