### PR TITLE
add embedded signup form from mailchimp

### PR DESCRIPTION
**Pull request by DanielSanchez97**
Switched to using an embedded mail chimp form to collect emails

### CODE REVIEW

**Comment by DanielSanchez97** [comment]
Please run this local branch and double check the new email workflow. Once confirmed, you can approve the change.

**Review by jtfrench23 — APPROVED** [review]
It works smoothly

**Comment by ianick87** [comment]
The email stuff worked for me. But I chcked the changes I made in the S3 bucket example and I don't see it. Is this branch up to date?

**Comment by DanielSanchez97** [comment]
@Pia007  I think that won't be a problem once it is in prod since the redirect from Mailchimp goes back to cdevframework.io instead of localhost.

**Comment by DanielSanchez97** [comment]
@ianick87 yea I haven't pull main into it since it was created, so the content of the site might not be all there. Once it is merged, it will be there

**Review by ianick87 — APPROVED** [review]

**Pull request merged**
