### PR TITLE
Settings

### PR DESCRIPTION
**Pull request by jtfrench23**
I added a section to this page that explains how to add and switch environments.  Let me know if you think this is a good addition and/or if you have any suggestions of information to add, fix, or remove.

### CODE REVIEW

**Comment by jtfrench23** [comment]
I accidentally brought over my changes on the nosqldb branch with this.

**Comment by jtfrench23** [comment]
the last commit has the changes to the settings md

**Review by Pia007 — CHANGES_REQUESTED** [review]
Hi Jordan, just on grammar change.

**Review by DanielSanchez97 — APPROVED** [review]
LGTM

**Pull request merged**
