### PR TITLE
updates to blog pages to make them look more like blogs

### PR DESCRIPTION
**Pull request by jtfrench23**

### CODE REVIEW

**Review by DanielSanchez97 — CHANGES_REQUESTED** [review]
Overall looked good, but I restructured the single blog pages a little bit. I didn't know how to describe what I wanted the page to look like, so I just made some changes to make it easier to understand what I am talking about. 

I think it would be cool to have a background image behind the raised container with the content of the blog. Right now, the image takes up the whole page, but in my head, it would only take up the top half of the page. but also scroll down with the blog as the user reads. 
Let me know if this doesn't make any sense! 

Other things:
Add a small headshot image somewhere on the blog page like on https://baselime.io/blog/baselime-raises-pre-seed. 
Add share on social buttons 
Make the list of blogs used raised cards like the `children-card-container.html` partial used on the /docs/example list page

**Review by ianick87 — APPROVED** [review]

**Comment by DanielSanchez97** [comment]
I just made a few quick changes that way we save a round trip. It looks good to me! 

Go ahead and turn off the workshop page for now. Comment it out or turn the pages off in Hugo then once this is merged and pushed, open another PR specifically for the workshop pages. We can then use that PR over the next few days to update just the workshop content and style.

**Comment by DanielSanchez97** [comment]
The office hour pages LGTM, but it looks like the Zoom link is dead for the office hours link. Did we ever make the official link for that on zoom?

**Comment by DanielSanchez97** [comment]
I changed a little bit of the padding on the single blog site, made the whole card on the list page to be a link, and added some styling to make it look better on mobile.

On mobile, there is still an issue with the styling. Specifically, the social buttons sometimes go off the page and mess up the formatting. It does not happen every time, but if you use the chrome dev tools and keep reloading the page it should come up. I'll leave that for you since you set up those links.

Once that small formatting issue is fixed, this will LGTM!

**Comment by jtfrench23** [comment]
I changed the responsiveness of the share buttons the only thing I don't really like is on the really small screen like galaxy fold there isn't enough space for the date to be in line with the author so it drops down and pushes the share buttons down with it.  We could make the date disappear for the xs screens but it may not be a big deal. Let me know what you think.

**Review by DanielSanchez97 — APPROVED** [review]
LGTM

**Review by ianick87 — COMMENTED** [review]
It's looking good!

**Pull request merged**
